language: java
jdk:
  - oraclejdk8
  - openjdk7
before_install:
  - mkdir -p ~/.gradle
  - echo "nexusUser=foo" > ~/.gradle/gradle.properties
  - echo "nexusPassword=bar" >> ~/.gradle/gradle.properties

